"""Central knowledge base for risk mapping rules."""

RISK_RULES = {
    "A03": {
        "title": "Injection",
        "signals": [
            {
                "concept": "user-controlled input fields",
                "terms": ["input", "field", "form", "registration form", "login form"],
                "abuse_cases": [
                    "Attacker injects script payload into form fields to attempt reflected or stored XSS.",
                    "Attacker submits crafted special characters to bypass weak validation and break parser logic.",
                ],
                "best_practices": [
                    "Validate and sanitize form input on the server side with strict allowlists.",
                    "Apply output encoding based on rendering context to prevent script execution.",
                ],
            },
            {
                "concept": "identity fields",
                "terms": [
                    "email",
                    "e-mail",
                    "username",
                    "user name",
                    "userid",
                    "user id",
                    "login id",
                    "account id",
                    "display name",
                    "bio",
                ],
                "abuse_cases": [
                    "Attacker injects payloads into identity fields to test for SQL or script injection handling weaknesses.",
                    "Attacker uses malformed identifier values to trigger unsafe backend query or parsing behavior.",
                ],
                "best_practices": [
                    "Use parameterized queries for all identity field lookups.",
                    "Normalize and validate identifier formats before processing.",
                ],
            },
            {
                "concept": "credential fields",
                "terms": [
                    "password",
                    "passcode",
                    "secretkey",
                    "secret key",
                    "userkey",
                    "user key",
                    "pin",
                ],
                "abuse_cases": [
                    "Attacker injects crafted input in credential fields to probe authentication query handling.",
                    "Attacker submits malformed credential payloads to discover weak server-side parsing paths.",
                ],
                "best_practices": [
                    "Treat credential fields as untrusted input and validate strictly on the server side.",
                    "Avoid building dynamic query strings with credential input.",
                ],
            },
            {
                "concept": "file upload inputs",
                "terms": [
                    "upload",
                    "file upload",
                    "profile picture",
                    "profile image",
                    "avatar",
                    "image",
                    "attachment",
                    "filename",
                    "multipart",
                ],
                "abuse_cases": [
                    "Attacker uploads a malicious file disguised as a profile image to attempt code execution or stored script injection.",
                    "Attacker manipulates file name or metadata to attempt path traversal during upload processing.",
                ],
                "best_practices": [
                    "Allowlist upload file types and verify MIME type plus magic bytes on the server side.",
                    "Rename uploaded files server-side and store them outside the web root with strict size limits.",
                ],
            },
        ],
        "abuse_cases": [
            "Attacker injects script payload into registration fields to attempt stored XSS.",
            "Attacker sends SQL-style payload in login inputs to test query manipulation.",
            "Attacker uses crafted characters to bypass weak server-side validation.",
            "Attacker uploads a malicious file disguised as a profile image to attempt code execution or stored script injection.",
            "Attacker manipulates file name or metadata to attempt path traversal during upload processing.",
        ],
        "best_practices": [
            "Validate user inputs on both client and server sides.",
            "Use parameterized queries and context-aware output encoding.",
            "For uploads, allowlist file types and verify MIME type plus magic bytes on the server side.",
            "Rename uploaded files server-side and store them outside the web root with strict size limits.",
        ],
    },
    "A07": {
        "title": "Identification and Authentication Failures",
        "signals": [
            {
                "concept": "authentication actions",
                "terms": [
                    "login",
                    "log in",
                    "signin",
                    "sign in",
                    "authenticate",
                    "authentication",
                    "register",
                    "signup",
                    "sign up",
                    "create account",
                    "onboarding",
                    "sign up with google",
                    "sign up with apple",
                    "sign up with github",
                ],
                "abuse_cases": [
                    "Attacker performs credential stuffing against login endpoints with reused leaked passwords.",
                    "Attacker enumerates valid users through different responses for existing and non-existing accounts.",
                    "Attacker bypasses weak login throttling by distributing attempts across many IPs or accounts.",
                ],
                "best_practices": [
                    "Use generic error messages for authentication outcomes.",
                    "Apply rate limiting and anomaly detection on login and registration endpoints.",
                    "Add risk-based authentication controls for suspicious login behavior.",
                ],
            },
            {
                "concept": "credential handling",
                "terms": [
                    "password",
                    "passcode",
                    "secretkey",
                    "secret key",
                    "userkey",
                    "user key",
                    "reset password",
                    "forgot password",
                    "password rotation",
                    "password strength meter",
                    "reset token",
                    "security question",
                ],
                "abuse_cases": [
                    "Attacker abuses weak password policy and quickly guesses user credentials.",
                    "Attacker intercepts or reuses weak reset tokens when password recovery controls are insufficient.",
                    "Attacker bypasses client-side password strength checks if server-side enforcement is missing.",
                ],
                "best_practices": [
                    "Use strong password hashing and enforce minimum entropy requirements.",
                    "Issue single-use, short-lived reset tokens and invalidate them after use.",
                    "Enforce password complexity and breach checks on the server side, not only in UI.",
                ],
            },
            {
                "concept": "session and verification",
                "terms": [
                    "session",
                    "session token",
                    "refresh token",
                    "cookie",
                    "active sessions",
                    "logout other devices",
                    "remember me",
                    "otp",
                    "mfa",
                    "2fa",
                    "totp",
                    "magic link",
                    "one time password",
                    "passwordless",
                    "biometric",
                    "webauthn",
                ],
                "abuse_cases": [
                    "Attacker reuses stolen persistent cookies from remember-me sessions.",
                    "Attacker replays OTP or magic link tokens when expiry and one-time-use controls are weak.",
                    "Attacker hijacks long-lived sessions when rotation and remote logout controls are missing.",
                    "Attacker exploits session fixation when the session ID is not rotated after authentication.",
                ],
                "best_practices": [
                    "Bind verification tokens to short expiry, one-time use, and intended user action.",
                    "Use secure, HttpOnly, SameSite cookies and rotate sessions after authentication events.",
                    "Revoke refresh tokens and terminate all linked sessions during sensitive security actions.",
                ],
            },
            {
                "concept": "federated identity and sso",
                "terms": [
                    "oauth",
                    "oauth2",
                    "openid",
                    "openid connect",
                    "oidc",
                    "social auth",
                    "google",
                    "apple",
                    "github",
                    "google login",
                    "login with google",
                    "sign in with google",
                    "sso",
                    "single sign on",
                    "redirect uri",
                    "oauth callback",
                    "state",
                    "nonce",
                    "id token",
                ],
                "abuse_cases": [
                    "Attacker abuses misconfigured OAuth redirect URIs to steal authorization codes or tokens.",
                    "Attacker forges identity assertions when token issuer, audience, or signature validation is weak.",
                    "Attacker replays a previously captured ID token when nonce and token lifecycle checks are missing.",
                    "Attacker performs login CSRF when state validation is not enforced on OAuth callback.",
                    "Attacker links their social identity to another local account through weak account-linking rules.",
                ],
                "best_practices": [
                    "Use strict redirect URI allowlists and validate state and nonce values.",
                    "Validate token signature, issuer, audience, and expiry before creating local sessions.",
                    "Rotate local session identifiers after successful federated login.",
                    "Require explicit, verified account-linking steps for existing local accounts.",
                ],
            },
            {
                "concept": "recovery and lockout",
                "terms": [
                    "account recovery",
                    "username recovery",
                    "forgot username",
                    "email verification",
                    "phone verification",
                    "account locking",
                    "unlock account",
                    "lockout",
                    "failed attempts",
                ],
                "abuse_cases": [
                    "Attacker triggers account lockout repeatedly to deny service to legitimate users.",
                    "Attacker abuses recovery flow to discover whether a specific email or phone is registered.",
                    "Attacker attempts brute-force guessing of weak verification or recovery codes.",
                ],
                "best_practices": [
                    "Design lockout controls to resist brute force while minimizing denial-of-service abuse.",
                    "Keep recovery responses uniform and avoid revealing account existence.",
                    "Rate-limit recovery attempts and invalidate outstanding recovery tokens after successful reset.",
                ],
            },
        ],
        "abuse_cases": [
            "Attacker brute-forces login due to missing rate limits or lockout.",
            "Attacker exploits weak password policy and reuses leaked credentials.",
            "Attacker abuses predictable or long-lived sessions after login.",
        ],
        "best_practices": [
            "Enforce strong password policy and secure password hashing.",
            "Apply login rate limiting and temporary lockout after repeated failures.",
        ],
    },
    "A01": {
        "title": "Broken Access Control",
        "signals": [
            {
                "concept": "role and permission controls",
                "terms": [
                    "role",
                    "roles",
                    "permission",
                    "permissions",
                    "authorize",
                    "authorization",
                    "admin",
                    "user management",
                    "role selection",
                    "account type",
                    "student",
                    "teacher",
                ],
                "abuse_cases": [
                    "User self-assigns privileged roles during registration by tampering with role selection parameters.",
                    "User accesses admin-only actions due to missing server-side authorization enforcement.",
                ],
                "best_practices": [
                    "Enforce role assignment on the server and ignore client-submitted privileged roles.",
                    "Apply deny-by-default authorization checks on every protected endpoint.",
                ],
            },
            {
                "concept": "protected account resources",
                "terms": [
                    "account",
                    "profile",
                    "dashboard",
                    "view other users",
                    "other user",
                    "own account",
                    "progressive profiling",
                ],
                "abuse_cases": [
                    "User manipulates object identifiers to view or modify another user's profile data.",
                    "User accesses progressive profile data that should only be visible to authorized actors.",
                ],
                "best_practices": [
                    "Implement object-level authorization checks for every account and profile operation.",
                    "Scope returned profile data to least privilege and ownership rules.",
                ],
            },
            {
                "concept": "session control actions",
                "terms": [
                    "active sessions",
                    "remote logout",
                    "logout other devices",
                ],
                "abuse_cases": [
                    "Attacker keeps unauthorized access if session invalidation does not revoke all related tokens.",
                    "User terminates sessions that do not belong to them when ownership checks are missing.",
                ],
                "best_practices": [
                    "Require strong ownership checks for session-management endpoints.",
                    "Invalidate refresh tokens and session artifacts across devices on remote logout.",
                ],
            },
        ],
        "abuse_cases": [
            "User modifies request parameters to access another user's account data.",
            "Normal user reaches admin-only screens due to missing authorization checks.",
            "User changes identifiers in URLs or forms to perform unauthorized actions.",
        ],
        "best_practices": [
            "Enforce authorization checks on every protected endpoint.",
            "Use server-side role checks and deny by default.",
        ],
    },
}
